/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagAlong2RouteImport } from './routes/tag-along-2'
import { Route as StayRouteImport } from './routes/stay'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as GatherRouteImport } from './routes/gather'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CafeRouteImport } from './routes/cafe'
import { Route as BackpackersRouteImport } from './routes/backpackers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TagAlong2Route = TagAlong2RouteImport.update({
  id: '/tag-along-2',
  path: '/tag-along-2',
  getParentRoute: () => rootRouteImport,
} as any)
const StayRoute = StayRouteImport.update({
  id: '/stay',
  path: '/stay',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const GatherRoute = GatherRouteImport.update({
  id: '/gather',
  path: '/gather',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeRoute = CafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const BackpackersRoute = BackpackersRouteImport.update({
  id: '/backpackers',
  path: '/backpackers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/backpackers': typeof BackpackersRoute
  '/cafe': typeof CafeRoute
  '/explore': typeof ExploreRoute
  '/gallery': typeof GalleryRoute
  '/gather': typeof GatherRoute
  '/people': typeof PeopleRoute
  '/stay': typeof StayRoute
  '/tag-along-2': typeof TagAlong2Route
  '/admin': typeof AuthenticatedAdminRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/backpackers': typeof BackpackersRoute
  '/cafe': typeof CafeRoute
  '/explore': typeof ExploreRoute
  '/gallery': typeof GalleryRoute
  '/gather': typeof GatherRoute
  '/people': typeof PeopleRoute
  '/stay': typeof StayRoute
  '/tag-along-2': typeof TagAlong2Route
  '/admin': typeof AuthenticatedAdminRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal': typeof JournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/backpackers': typeof BackpackersRoute
  '/cafe': typeof CafeRoute
  '/explore': typeof ExploreRoute
  '/gallery': typeof GalleryRoute
  '/gather': typeof GatherRoute
  '/people': typeof PeopleRoute
  '/stay': typeof StayRoute
  '/tag-along-2': typeof TagAlong2Route
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/backpackers'
    | '/cafe'
    | '/explore'
    | '/gallery'
    | '/gather'
    | '/people'
    | '/stay'
    | '/tag-along-2'
    | '/admin'
    | '/journal/$slug'
    | '/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/backpackers'
    | '/cafe'
    | '/explore'
    | '/gallery'
    | '/gather'
    | '/people'
    | '/stay'
    | '/tag-along-2'
    | '/admin'
    | '/journal/$slug'
    | '/journal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/backpackers'
    | '/cafe'
    | '/explore'
    | '/gallery'
    | '/gather'
    | '/people'
    | '/stay'
    | '/tag-along-2'
    | '/_authenticated/admin'
    | '/journal/$slug'
    | '/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BackpackersRoute: typeof BackpackersRoute
  CafeRoute: typeof CafeRoute
  ExploreRoute: typeof ExploreRoute
  GalleryRoute: typeof GalleryRoute
  GatherRoute: typeof GatherRoute
  PeopleRoute: typeof PeopleRoute
  StayRoute: typeof StayRoute
  TagAlong2Route: typeof TagAlong2Route
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tag-along-2': {
      id: '/tag-along-2'
      path: '/tag-along-2'
      fullPath: '/tag-along-2'
      preLoaderRoute: typeof TagAlong2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stay': {
      id: '/stay'
      path: '/stay'
      fullPath: '/stay'
      preLoaderRoute: typeof StayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gather': {
      id: '/gather'
      path: '/gather'
      fullPath: '/gather'
      preLoaderRoute: typeof GatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe': {
      id: '/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof CafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backpackers': {
      id: '/backpackers'
      path: '/backpackers'
      fullPath: '/backpackers'
      preLoaderRoute: typeof BackpackersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BackpackersRoute: BackpackersRoute,
  CafeRoute: CafeRoute,
  ExploreRoute: ExploreRoute,
  GalleryRoute: GalleryRoute,
  GatherRoute: GatherRoute,
  PeopleRoute: PeopleRoute,
  StayRoute: StayRoute,
  TagAlong2Route: TagAlong2Route,
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
