-- Ensure one slug per page so article links stay unique after export
CREATE UNIQUE INDEX IF NOT EXISTS cms_entries_page_slug_key
  ON public.cms_entries (page, slug)
  WHERE slug IS NOT NULL;

-- Reseed Journal + Gallery demo content (idempotent on re-run)
DELETE FROM public.cms_entries WHERE page IN ('journal', 'gallery');

INSERT INTO public.cms_entries (page, section, position, slug, status, published_at, seo_title, seo_description, image_url, data) VALUES
('journal','featured',0,'the-fog-arrives-at-four','published', now(),
 'The fog arrives at four — Tag Along Journal',
 'A slow essay about the hour the valley disappears and the house fills up again.',
 'hero-window',
 '{"kicker":"Essay","title":"The fog arrives at four","excerpt":"Every afternoon the valley disappears for an hour. Nobody leaves. The kettle goes on, someone finds the guitar, and the house does the thing it does best.","by":"Dipesh","date":"June 2026","read":"6 min","link":"/journal/the-fog-arrives-at-four","body":"At four the light goes flat and the ridge behind the house simply stops existing. It is not dramatic. There is no wind. The fog walks up from Ranipool the way a neighbour walks up — slowly, without knocking.\n\nInside, the afternoon reorganises itself. The people who said they were leaving for Tsomgo stay. The kettle goes on twice. Someone finds the guitar with the taped headstock and plays three chords badly for twenty minutes until somebody better takes it.\n\nWe have stopped apologising for the weather. The fog is the best thing that happens here. It is the only hour of the day when nobody is going anywhere, and nine years of this house have taught us that this is when the good conversations start."}'::jsonb),

('journal','notes',0,'bread-day','published', now(),
 'Bread day — Tag Along Journal',
 'Wednesday is bread day. It rarely works. We do it anyway.',
 'gallery-food',
 '{"date":"12.06","title":"Bread day","by":"Binita","read":"3 min","body":"Wednesday is bread day, which mostly means the kitchen is unusable from ten to two and the loaf comes out dense enough to prop a door.\n\nWe keep doing it because the twenty minutes of kneading is the only time guests talk to each other without asking where anyone is from."}'::jsonb),
('journal','notes',1,'the-guitar-with-the-taped-headstock','published', now(),
 'The guitar with the taped headstock — Tag Along Journal',
 'One instrument, four owners, nine years and a lot of tape.',
 'gallery-events',
 '{"date":"29.05","title":"The guitar with the taped headstock","by":"Shekar","read":"4 min","body":"It arrived with a French cyclist who could not carry it further. It has been restrung by at least four people, dropped down the stairwell once, and repaired with the kind of tape you use on parcels.\n\nIt is not a good guitar. It is the most used object in the building."}'::jsonb),
('journal','notes',2,'what-the-monsoon-teaches','published', now(),
 'What the monsoon teaches — Tag Along Journal',
 'Six weeks of rain, and the small rearrangements it forces.',
 'gallery-experiences',
 '{"date":"14.05","title":"What the monsoon teaches","by":"Sumiran","read":"5 min","body":"The rain does not ruin plans here so much as replace them. Walks become card games. Card games become dinners that run to midnight.\n\nBy the third week you stop checking the forecast, which is roughly the point of coming to the mountains at all."}'::jsonb),
('journal','notes',3,'a-list-of-things-left-behind','published', now(),
 'A list of things left behind — Tag Along Journal',
 'An honest inventory of the lost-and-found drawer.',
 'postcard-polaroid',
 '{"date":"02.05","title":"A list of things left behind","by":"Prabat","read":"2 min","body":"One left boot. Fourteen chargers. A hardback copy of a book about Ladakh with a phone number written inside the cover. Three notebooks we have not read and will not read.\n\nWe keep everything for a season. Most of it is never claimed, which we choose to read as a compliment."}'::jsonb),

('journal','photo_essays',0,'rooms-of-light','published', now(),
 'Rooms of light — Tag Along Journal',
 'A photo essay on the seven minutes of morning sun the dorm gets in winter.',
 'hero-window',
 '{"title":"Rooms of light","by":"Zeyma Studio","img":"hero-window","body":"Shot over four winter mornings on expired film. The dorm gets direct sun for roughly seven minutes in December, somewhere between 8:40 and 8:47, and everyone who has stayed through a winter here knows exactly where to stand."}'::jsonb),
('journal','photo_essays',1,'the-long-table','published', now(),
 'The long table — Tag Along Journal',
 'Twelve Wednesdays photographed from the same chair.',
 'gallery-community',
 '{"title":"The long table","by":"Rachna Books","img":"postcard-polaroid","body":"The same frame, the same chair, twelve Wednesday dinners. Different people every time except two: Binita, and the dog who does not live here."}'::jsonb),
('journal','photo_essays',2,'walking-to-radio-dara','published', now(),
 'Walking to Radio Dara — Tag Along Journal',
 'Two and a half hours uphill, photographed badly and happily.',
 'gallery-experiences',
 '{"title":"Walking to Radio Dara","by":"Tsal Studio","img":"gallery-experiences","body":"Two and a half hours up through pine, most of it in cloud. The photographs are out of focus because everybody was out of breath."}'::jsonb),

('journal','local_voices',0,'the-carpenter-who-built-the-bunks','published', now(),
 'The carpenter who built the bunks — Tag Along Journal',
 'Two streets away, thirty years of work, and our twenty-four beds.',
 'room-dorm',
 '{"title":"The carpenter who built the bunks","by":"as told to Dipesh","body":"His workshop is two streets down, behind the tailor. He has been making furniture in Gangtok for thirty-one years and thinks our bunk design is sentimental.\n\nHe built all twenty-four beds anyway, and comes by every few months to check that nothing has come loose."}'::jsonb),
('journal','local_voices',1,'a-bookshop-that-refuses-to-modernise','published', now(),
 'A bookshop that refuses to modernise — Tag Along Journal',
 'On Rachna Books, and the value of staying exactly as you are.',
 'gallery-community',
 '{"title":"A bookshop that refuses to modernise","by":"Rachna Books","body":"No app, no delivery, no plans for either. What it has instead is a person who remembers what you bought last year and has already set aside the thing you will buy next."}'::jsonb),
('journal','local_voices',2,'notes-from-the-momo-counter','published', now(),
 'Notes from the momo counter — Tag Along Journal',
 'Four hundred momos a day, six days a week, from a counter near MG Marg.',
 'gallery-food',
 '{"title":"Notes from the momo counter","by":"as told to Binita","body":"Four hundred a day, six days a week, twenty-two years. She opens at eleven and closes when the tray is empty, which in winter is by two."}'::jsonb),
('journal','local_voices',3,'the-last-fluent-speaker-on-our-street','published', now(),
 'The last fluent speaker on our street — Tag Along Journal',
 'A conversation about Lepcha, memory and what a street loses quietly.',
 'postcard-polaroid',
 '{"title":"The last fluent speaker on our street","by":"Nepali Sahitya Parishad","body":"A short conversation, recorded on a phone on a Tuesday, about a language that used to be the first thing you heard walking up this hill."}'::jsonb),

-- Gallery: editable filter categories
('gallery','categories',0,NULL,'published', now(), NULL, NULL, NULL, '{"name":"Backpackers"}'::jsonb),
('gallery','categories',1,NULL,'published', now(), NULL, NULL, NULL, '{"name":"Tag Along 2.0"}'::jsonb),
('gallery','categories',2,NULL,'published', now(), NULL, NULL, NULL, '{"name":"Travel Café"}'::jsonb),
('gallery','categories',3,NULL,'published', now(), NULL, NULL, NULL, '{"name":"Experiences"}'::jsonb),
('gallery','categories',4,NULL,'published', now(), NULL, NULL, NULL, '{"name":"Events"}'::jsonb),
('gallery','categories',5,NULL,'published', now(), NULL, NULL, NULL, '{"name":"Food"}'::jsonb),
('gallery','categories',6,NULL,'published', now(), NULL, NULL, NULL, '{"name":"Community"}'::jsonb),

-- Gallery: photos
('gallery','photos',0,NULL,'published', now(), NULL, NULL, 'room-dorm', '{"caption":"Bunks made by a carpenter two streets away","category":"Backpackers","meta":"The Bunk Room · March"}'::jsonb),
('gallery','photos',1,NULL,'published', now(), NULL, NULL, 'gallery-community', '{"caption":"Wednesday dinner, cooked by whoever showed up","category":"Community","meta":"Long table · April"}'::jsonb),
('gallery','photos',2,NULL,'published', now(), NULL, NULL, 'hero-window', '{"caption":"Fog arriving before the second coffee","category":"Tag Along 2.0","meta":"Window seat · June"}'::jsonb),
('gallery','photos',3,NULL,'published', now(), NULL, NULL, 'gallery-food', '{"caption":"Shakshouka and buckwheat crepes","category":"Food","meta":"Travel Café · Mornings"}'::jsonb),
('gallery','photos',4,NULL,'published', now(), NULL, NULL, 'gallery-events', '{"caption":"Live music night, three songs in","category":"Events","meta":"Common room · Saturday"}'::jsonb),
('gallery','photos',5,NULL,'published', now(), NULL, NULL, 'gallery-experiences', '{"caption":"The pine trail towards Radio Dara","category":"Experiences","meta":"Gangtok · Monsoon"}'::jsonb),
('gallery','photos',6,NULL,'published', now(), NULL, NULL, 'room-lounge', '{"caption":"The lounge in its favourite hour","category":"Backpackers","meta":"4pm chai"}'::jsonb),
('gallery','photos',7,NULL,'published', now(), NULL, NULL, 'room-private', '{"caption":"The balcony room, curtains open","category":"Tag Along 2.0","meta":"Valley side"}'::jsonb),
('gallery','photos',8,NULL,'published', now(), NULL, NULL, 'postcard-polaroid', '{"caption":"Polaroids left behind by people we miss","category":"Community","meta":"Wall of strangers"}'::jsonb),
('gallery','photos',9,NULL,'published', now(), NULL, NULL, 'gallery-food', '{"caption":"Hazelnut latte, one sugar, no rush","category":"Travel Café","meta":"Counter · Any day"}'::jsonb),
('gallery','photos',10,NULL,'published', now(), NULL, NULL, 'gallery-events', '{"caption":"Trivia night arguments","category":"Events","meta":"Thursdays"}'::jsonb),
('gallery','photos',11,NULL,'published', now(), NULL, NULL, 'gallery-experiences', '{"caption":"A local''s loop, halfway up","category":"Experiences","meta":"2.5 hours"}'::jsonb);
